version: '3.6'
services:
  vault:
    image: vault:1.13.3
    container_name: vault
    ports:
      - "8201:8201"
      - "8200:8200"
    environment:
      VAULT_ADDR: 'http://127.0.0.1:8201'
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8201","tls_disable":"1", "tls_cert_file":"/data/certs/cert.pem", "tls_key_file":"/data/certs/key.pem"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
      VAULT_DEV_ROOT_TOKEN_ID: 'secret-token'
      VAULT_TOKEN: 'secret-token'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./docker:/data
    command: server -dev -dev-root-token-id="00000000-0000-0000-0000-000000000000"
    networks:
      - my_vault

networks:
  my_vault:
    external: true
